extern _Bool var_17;
extern int var_18;
extern signed char var_19;
extern unsigned long long int var_20;
extern int var_21;
extern short var_22;
extern int var_23;
extern unsigned long long int var_24;
extern int var_25;
extern unsigned long long int var_26;
extern unsigned char var_27;
extern int var_28;
extern unsigned long long int var_29;
extern _Bool var_30;
extern signed char var_31;
extern unsigned long long int var_32;
extern unsigned char var_33;
extern int var_34;
extern unsigned char var_35;
extern unsigned long long int var_36;
extern long long int arr_8 [24] ;
extern short arr_9 [24] [24] [24] [24] ;
extern unsigned long long int arr_10 [24] [24] [24] ;
