extern signed char var_17;
extern unsigned char var_18;
extern unsigned short var_19;
extern long long int var_20;
extern long long int var_21;
extern unsigned char var_22;
extern long long int var_23;
extern unsigned char var_24;
extern unsigned char var_25;
extern unsigned int var_26;
extern long long int var_27;
extern unsigned char var_28;
extern unsigned char var_29;
extern long long int var_30;
extern unsigned int var_31;
extern long long int var_32;
extern unsigned short var_33;
extern unsigned short var_34;
extern unsigned int var_35;
extern long long int var_36;
extern unsigned char var_37;
extern long long int var_38;
extern unsigned char var_39;
extern unsigned char var_40;
extern unsigned int var_41;
extern unsigned short var_42;
extern unsigned char var_43;
extern unsigned short var_44;
extern unsigned char var_45;
extern unsigned char var_46;
extern unsigned char var_47;
extern unsigned char var_48;
extern long long int var_49;
extern long long int var_50;
extern signed char var_51;
extern long long int var_52;
extern unsigned char var_53;
extern unsigned char var_54;
extern unsigned char var_55;
extern long long int var_56;
extern signed char var_57;
extern long long int var_58;
extern signed char var_59;
extern unsigned int var_60;
extern unsigned int var_61;
extern unsigned int var_62;
extern signed char var_63;
extern unsigned int var_64;
extern long long int var_65;
extern long long int var_66;
extern unsigned int var_67;
extern unsigned char var_68;
extern signed char var_69;
extern unsigned char var_70;
extern signed char var_71;
extern unsigned short var_72;
extern signed char var_73;
extern unsigned int var_74;
extern unsigned int var_75;
extern unsigned int var_76;
extern signed char var_77;
extern unsigned int var_78;
extern unsigned char var_79;
extern unsigned short var_80;
extern long long int var_81;
extern unsigned char var_82;
extern long long int var_83;
extern unsigned char var_84;
extern unsigned int var_85;
extern signed char var_86;
extern unsigned char var_87;
extern unsigned short var_88;
extern signed char var_89;
extern unsigned char var_90;
extern signed char var_91;
extern unsigned short var_92;
extern unsigned char var_93;
extern unsigned int var_94;
extern long long int var_95;
extern unsigned short var_96;
extern unsigned short var_97;
extern long long int var_98;
extern unsigned int var_99;
extern unsigned short var_100;
extern unsigned int var_101;
extern unsigned char var_102;
extern unsigned short var_103;
extern unsigned char var_104;
extern signed char var_105;
extern unsigned short var_106;
extern signed char var_107;
extern signed char var_108;
extern long long int var_109;
extern unsigned short var_110;
extern unsigned char var_111;
extern signed char var_112;
extern unsigned char var_113;
extern unsigned char var_114;
extern long long int var_115;
extern long long int var_116;
extern signed char var_117;
extern unsigned char var_118;
extern unsigned int var_119;
extern unsigned int var_120;
extern unsigned char var_121;
extern long long int var_122;
extern unsigned int var_123;
extern unsigned int var_124;
extern unsigned int var_125;
extern unsigned char var_126;
extern unsigned char var_127;
extern unsigned char var_128;
extern unsigned int var_129;
extern unsigned int var_130;
extern signed char arr_11 [22] [22] [22] ;
extern unsigned int arr_16 [22] [22] [22] [22] ;
extern long long int arr_29 [22] [22] [22] ;
extern unsigned int arr_30 [22] [22] [22] [22] [22] ;
extern long long int arr_36 [22] [22] [22] [22] [22] [22] [22] ;
extern unsigned int arr_40 [22] [22] ;
extern signed char arr_45 [22] [22] [22] [22] [22] ;
extern signed char arr_50 [22] [22] [22] [22] ;
extern unsigned short arr_53 [22] [22] [22] ;
extern unsigned int arr_67 [22] [22] [22] [22] [22] ;
extern unsigned char arr_68 [22] [22] ;
extern signed char arr_73 [22] [22] ;
