extern long long int var_17;
extern int var_18;
extern signed char var_19;
extern unsigned int var_20;
extern int var_21;
extern signed char var_22;
extern signed char var_23;
extern unsigned long long int var_24;
extern signed char var_25;
extern unsigned long long int arr_15 [19] ;
extern int arr_16 [19] ;
