extern long long int var_16;
extern int var_17;
extern int var_18;
extern int var_19;
extern short var_20;
extern _Bool var_21;
extern long long int var_22;
extern short var_23;
extern short arr_3 [15] ;
extern unsigned long long int arr_8 [19] [19] ;
extern unsigned int arr_9 [19] [19] ;
