extern _Bool var_17;
extern int var_18;
extern signed char var_19;
extern signed char var_20;
extern signed char var_21;
extern int var_22;
extern unsigned char var_23;
extern _Bool var_24;
extern unsigned short var_25;
extern int var_26;
extern unsigned short var_27;
extern unsigned short var_28;
extern unsigned short var_29;
extern unsigned int var_30;
extern int var_31;
extern unsigned long long int var_32;
extern _Bool var_33;
extern signed char var_34;
extern unsigned int var_35;
extern short var_36;
extern unsigned int var_37;
extern int var_38;
extern _Bool var_39;
extern unsigned short var_40;
extern unsigned short var_41;
extern unsigned int var_42;
extern unsigned short var_43;
extern unsigned long long int var_44;
extern _Bool var_45;
extern short var_46;
extern unsigned int var_47;
extern unsigned long long int var_48;
extern unsigned long long int var_49;
extern unsigned long long int var_50;
