extern unsigned int var_12;
extern short var_13;
extern unsigned char var_14;
extern long long int var_15;
extern unsigned char var_16;
extern unsigned char var_17;
extern unsigned long long int var_18;
extern int var_19;
extern long long int var_20;
extern _Bool var_21;
extern short var_22;
extern int var_23;
