extern int var_11;
extern unsigned char var_12;
extern unsigned long long int var_13;
extern unsigned long long int var_14;
extern signed char var_15;
extern unsigned char var_16;
extern unsigned long long int var_17;
extern unsigned long long int var_18;
extern signed char var_19;
extern signed char var_20;
extern unsigned short var_21;
extern int var_22;
extern unsigned int var_23;
extern unsigned char var_24;
extern signed char var_25;
extern unsigned long long int var_26;
extern unsigned long long int var_27;
extern short var_28;
extern signed char var_29;
extern unsigned long long int var_30;
extern _Bool var_31;
extern unsigned int var_32;
extern short var_33;
extern long long int var_34;
extern unsigned int var_35;
extern unsigned char var_36;
extern long long int var_37;
extern unsigned char var_38;
extern long long int var_39;
extern unsigned char var_40;
extern signed char var_41;
extern unsigned long long int var_42;
extern _Bool var_43;
extern unsigned short var_44;
extern unsigned long long int var_45;
extern long long int var_46;
extern unsigned int var_47;
extern signed char var_48;
extern signed char var_49;
extern unsigned char var_50;
extern long long int var_51;
extern unsigned long long int var_52;
extern unsigned char var_53;
extern unsigned int var_54;
extern unsigned char arr_5 [22] ;
extern unsigned long long int arr_12 [22] [22] ;
extern long long int arr_26 [22] [22] [22] [22] [22] [22] ;
extern long long int arr_29 [22] ;
extern unsigned long long int arr_32 [22] [22] [22] ;
extern unsigned char arr_33 [22] [22] ;
extern unsigned char arr_53 [22] [22] [22] [22] [22] [22] ;
extern unsigned char arr_54 [22] [22] [22] [22] [22] ;
