extern short var_19;
extern long long int var_20;
extern unsigned long long int var_21;
extern long long int var_22;
extern long long int var_23;
extern short var_24;
extern unsigned int var_25;
extern long long int var_26;
extern unsigned int var_27;
extern int var_28;
extern _Bool var_29;
extern short var_30;
extern unsigned int var_31;
extern unsigned long long int var_32;
extern int var_33;
extern unsigned long long int var_34;
extern unsigned int arr_9 [17] [17] ;
extern unsigned long long int arr_10 [17] ;
extern int arr_20 [17] ;
extern unsigned int arr_21 [17] [17] [17] [17] [17] ;
