extern int var_11;
extern _Bool var_12;
extern short var_13;
extern unsigned int var_14;
extern unsigned long long int var_15;
extern signed char var_16;
extern int var_17;
extern unsigned char var_18;
extern unsigned short arr_5 [16] ;
extern int arr_9 [19] ;
