extern unsigned long long int var_11;
extern int var_12;
extern unsigned long long int var_13;
extern int var_14;
extern unsigned long long int var_15;
extern signed char var_16;
extern _Bool var_17;
extern int var_18;
extern unsigned long long int var_19;
extern unsigned long long int var_20;
extern unsigned long long int var_21;
extern int var_22;
extern signed char var_23;
extern int var_24;
extern _Bool var_25;
extern _Bool var_26;
extern unsigned long long int var_27;
extern int var_28;
extern long long int var_29;
extern short var_30;
extern _Bool var_31;
extern signed char var_32;
extern signed char var_33;
extern _Bool var_34;
extern unsigned long long int var_35;
extern signed char var_36;
extern long long int var_37;
extern unsigned long long int var_38;
extern unsigned long long int var_39;
extern unsigned short arr_5 [20] [20] ;
extern signed char arr_13 [20] [20] [20] ;
