extern unsigned char var_10;
extern unsigned char var_11;
extern _Bool var_12;
extern long long int var_13;
extern unsigned char var_14;
extern unsigned char var_15;
extern unsigned char var_16;
extern unsigned char var_17;
extern unsigned long long int var_18;
extern _Bool arr_15 [23] [23] [23] ;
