extern unsigned int var_15;
extern _Bool var_16;
extern long long int var_17;
extern unsigned short var_18;
extern int var_19;
extern long long int var_20;
extern signed char var_21;
extern short var_22;
extern unsigned long long int var_23;
extern signed char var_24;
extern signed char var_25;
