extern int var_10;
extern _Bool var_11;
extern signed char var_12;
extern unsigned int var_13;
extern _Bool var_14;
extern unsigned short var_15;
extern unsigned short var_16;
extern long long int var_17;
extern unsigned int var_18;
extern _Bool var_19;
extern unsigned int var_20;
extern unsigned short var_21;
extern signed char var_22;
extern unsigned short var_23;
extern unsigned short var_24;
extern _Bool var_25;
extern signed char var_26;
extern signed char var_27;
extern unsigned int var_28;
extern _Bool var_29;
extern _Bool var_30;
extern int var_31;
extern long long int var_32;
extern long long int var_33;
extern unsigned int var_34;
extern unsigned long long int var_35;
extern unsigned long long int var_36;
extern signed char var_37;
extern unsigned long long int var_38;
extern unsigned short var_39;
extern unsigned short var_40;
extern signed char var_41;
extern unsigned short var_42;
extern _Bool var_43;
extern signed char var_44;
extern signed char var_45;
