extern signed char var_10;
extern unsigned long long int var_11;
extern int var_12;
extern unsigned int var_13;
extern unsigned char var_14;
extern unsigned char var_15;
extern unsigned char var_16;
extern _Bool var_17;
extern _Bool var_18;
extern int var_19;
extern short var_20;
extern unsigned int var_21;
extern signed char var_22;
extern signed char var_23;
extern signed char var_24;
extern unsigned char var_25;
extern signed char var_26;
extern unsigned char var_27;
extern signed char var_28;
extern int var_29;
extern int var_30;
extern int var_31;
extern int var_32;
extern unsigned char var_33;
extern _Bool var_34;
extern signed char var_35;
extern short var_36;
extern unsigned char var_37;
extern unsigned char var_38;
extern _Bool var_39;
extern signed char var_40;
extern signed char var_41;
extern unsigned char var_42;
extern _Bool var_43;
extern unsigned char var_44;
extern unsigned char var_45;
extern unsigned long long int arr_18 [21] ;
extern signed char arr_25 [13] ;
extern int arr_31 [13] ;
